### ISSUE TITLE
Jquery sortable

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-extensions-bundle#3]
Can we add back jquery-sortable that was remove with this commit.
We use it in both Magento and wordpress backend now

**Comment by maxiloc** [comment]
https://github.com/algolia/algoliasearch-extensions-bundle/commit/6d080adf5ac8bd480dba479c4c05759a779174d3

**Comment by Jerska** [comment]
Where are they using Sortable in the front-end?

**Comment by maxiloc** [comment]
no it's not in the frontend. It was in the bundle because jquery was encapsulated in the bundle so can not use jquery-sortable (in the admin panel) without the bundle

**Comment by Jerska** [comment]
Alright, but why do you need it in the bundle? Are you using the bundle in the back-end?

**Comment by maxiloc** [comment]
Yes I am using jquery in the backend config page. And because there is potential conflict(s) with prototype.js and/or other jquery I am using the bundle that encapsulate that.

**Comment by Jerska** [comment]
I'm not using the bundle, so that will be your call, but I strongly believe we shouldn't add unnecessary scripts to this bundle which was designed for the front-end if I'm not mistaken and is already big.

**Comment by redox** [comment]
> I'm not using the bundle, so that will be your call, but I strongly believe we shouldn't add unnecessary scripts to this bundle which was designed for the front-end if I'm not mistaken and is already big.

Agree, let's keep that outside of the bundle. I assume it's fine to add it as a dependency of our Magento extension, right?

**Comment by maxiloc** [comment]
I am ok with an admin bundle but I will need a encapsulated jquery and jquery-sortable for magento and wordpress to avoid conflicts

**Comment by vvo** [comment]
So you need a algoliasearch-extensions-admin-bundle? Should be easy to create this package, you can take the previous package state and copy paste and publish to npm :D

**Comment by redox** [comment]
I wouldn't even publish anything to NPM, just take the buildscript and use it in the Magento repository?

**Comment by vvo** [comment]
I think it's needed in both magento and wordpress. Npm here just being the easy way to share it between the two projects.

**Comment by maxiloc** [comment]
ok works for me. For now it's ok since jquery-sortable is in the current bundle of magento. But I will need that when we will merge instantsearch.js branch since the bundle doesn't have it anymore.

**Comment by maxiloc** [comment]
close with 0e2f97d1078da1d008d4b5da428e5a5416770733
